### ISSUE TITLE
QZXing examples and QT 5.14.2

### ISSUE THREAD

**Issue by rafalsk** [ftylitak/qzxing#169]
Hello,

We've been trying to compile QZXingLive example on QT 5.14.2, when deployed on Android API 24.

We can't get over a runtime error: 
`ftylitak.qzxin: Late-enabling -Xcheck:jni
I ftylitak.qzxin: The ClassLoaderContext is a special shared library.
E ftylitak.qzxin: Invalid ID 0x00000000.
E Qt      : Can't create main activity
E Qt      : android.content.res.Resources$NotFoundException: String array resource ID #0x0
E Qt      : 	at android.content.res.Resources.getStringArray(Resources.java:600)
E Qt      : 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:423)
E Qt      : 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:166)
E Qt      : 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:266)
E Qt      : 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:273)
E Qt      : 	at android.app.Activity.performCreate(Activity.java:7327)
E Qt      : 	at android.app.Activity.performCreate(Activity.java:7318)
E Qt      : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
E Qt      : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
E Qt      : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
E Qt      : 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E Qt      : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E Qt      : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E Qt      : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
E Qt      : 	at android.os.Handler.dispatchMessage(Handler.java:106)
E Qt      : 	at android.os.Looper.loop(Looper.java:214)
E Qt      : 	at android.app.ActivityThread.main(ActivityThread.java:7063)
E Qt      : 	at java.lang.reflect.Method.invoke(Native Method)
E Qt      : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E Qt      : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
I DecorView: createDecorCaptionView >> DecorView@c1bd4af[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D OpenGLRenderer: Skia GL Pipeline`

All we get is a white screen. The issue seems to be related to https://bugreports.qt.io/browse/QTBUG-80266
and https://stackoverflow.com/questions/59472866/qt-qml-for-android-bugs

any idea how to get over this? We've spent quite a lot of time on this one..

**Comment by ftylitak** [comment]
Hello @rafalsk 

thank you for your report. In the links that you have added it states that this happened due to changes in the integration of Qt to Android and can be fixed if the AnroidManifest.xml is regenerated. 

I will do this on Tuesday (09/06) since i do not have access right now. 

Till then if you are interested in giving a try yourself, the procedure is as follows: 
* Open a QZXingLive example with Qt Creator
* Keep a copy of file: examples/QZXingLive/android/AndroidManifest.xml
* Go to Projects > Build > Build Android APK > Details.
* Press button "Create Templates"
    * This will generate a new AndroidManifest.xml
* Based on the new AndroidManifest.xml try to adapt its contents with the project specific content of initial version of AndroidManifest.xml that we kept at step 2.

**Comment by rafalsk** [comment]
@ftylitak thank you for your prompt response, like I've said we've spent some quite time already trying to mitigate the issue in such a way -> to no avail, still we should keep trying till 09/06 if that is when you'll have some opportunity to take a look, if we come up with something I'll let you know.

**Comment by rafalsk** [comment]
Good news @ftylitak we got over it. what it took
1)Removed gradle-related files (possibly others, we left only the Java files + resources) from Android folder (besides the Manifest file), and recreated Manifest and others using  the 'Create Template' button (we had been doing this previously still  manifest alone was not enough).

2) Then we've encountered another error, which I think should be implemented as a warning according to QT's recent docs:
`E Qt      : extract_android_style option set to "none" when targetSdkVersion is less then 28`

Thus setting `       <meta-data android:name="android.app.extract_android_style" android:value="none"/>`
resolved it.

Now there are some warning such as `W System  : ClassLoader referenced unknown path`
BUT, the example works just fine, scanned a bar-code from a white cheese's packaging  a sec ago.
